// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:692441432773:android:1bfb040843e7eb0b9566ac',
    messagingSenderId: '692441432773',
    projectId: 'agroalchemy-9394d',
    authDomain: 'agroalchemy-9394d.firebaseapp.com',
    storageBucket: 'agroalchemy-9394d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkDnZ9Q4WxRl0hX5rLC8jC851tbgsG6k0',
    appId: '1:692441432773:android:1bfb040843e7eb0b9566ac',
    messagingSenderId: '692441432773',
    projectId: 'agroalchemy-9394d',
    storageBucket: 'agroalchemy-9394d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkDnZ9Q4WxRl0hX5rLC8jC851tbgsG6k0',
    appId: '1:692441432773:android:1bfb040843e7eb0b9566ac',
    messagingSenderId: '692441432773',
    projectId: 'agroalchemy-9394d',
    storageBucket: 'agroalchemy-9394d.firebasestorage.app',
    iosBundleId: 'com.example.agroAlchemy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkDnZ9Q4WxRl0hX5rLC8jC851tbgsG6k0',
    appId: '1:692441432773:android:1bfb040843e7eb0b9566ac',
    messagingSenderId: '692441432773',
    projectId: 'agroalchemy-9394d',
    storageBucket: 'agroalchemy-9394d.firebasestorage.app',
    iosBundleId: 'com.example.agroAlchemy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkDnZ9Q4WxRl0hX5rLC8jC851tbgsG6k0',
    appId: '1:692441432773:android:1bfb040843e7eb0b9566ac',
    messagingSenderId: '692441432773',
    projectId: 'agroalchemy-9394d',
    authDomain: 'agroalchemy-9394d.firebaseapp.com',
    storageBucket: 'agroalchemy-9394d.firebasestorage.app',
  );
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDkDnZ9Q4WxRl0hX5rLC8jC851tbgsG6k0',
    appId: '1:692441432773:android:1bfb040843e7eb0b9566ac',
    messagingSenderId: '692441432773',
    projectId: 'agroalchemy-9394d',
    authDomain: 'agroalchemy-9394d.firebaseapp.com',
    storageBucket: 'agroalchemy-9394d.firebasestorage.app',
  );
}
